### ISSUE TITLE
Software Orchestration blueprint 

### ISSUE THREAD

**Issue by fprezado** [eclipse-sdv-blueprints/blueprints#10]
### **Goal** 
This blueprint aims to showcase an example of how a proposed in-vehicle software orchestration architecture with connectivity to the cloud can help developers build and manage complex services and applications that tackle advanced scenarios like workload orchestration, scheduling, placement and resilience. The abstraction layers provided by the blueprint aim to simplify and enhance the developer experience. These include discovery and consumption of resources and services, support for a common vehicle model to be used across vehicles, dynamic topic management for publish and subscribe of vehicle signals and synchronization of signals to a cloud digital twin.

### **Use Case** 
The system detects that a smart trailer is being connected to the car. A signal is raised to the orchestrator that a smart trailer provider and application is required to manage the smart trailer and adjust body functions and powertrain accordingly and ensure a smooth trip.*

### **Projects** 
Eclipse Bluechi, Ankaios, Chariott, Ibeji, Freyja, Agemo and Kanto

### **Roadmap**
- **Phase 1:** In the first phase, we will show single and multi-node orchestration through an implementation with Eclipse Ankaios and another implementation with Eclipse BlueChi.

![image](https://github.com/eclipse-sdv-blueprints/blueprints/assets/9027586/4e37b961-9ff6-4f6f-a370-18734b54ca63)
![image](https://github.com/eclipse-sdv-blueprints/blueprints/assets/9027586/5b6d0341-1902-4934-98bc-bf604d4a99c3)

- **Phases 2 and 3:** Looking forward, in the second phase, we will target multi-domain orchestration and integrate with project Kanto. In the third phase, we will target the Cloud services for OTA.

![image](https://github.com/eclipse-sdv-blueprints/blueprints/assets/9027586/135b8d23-c631-47db-9b1c-06b4e0521a35)
![image](https://github.com/eclipse-sdv-blueprints/blueprints/assets/9027586/e724d0f2-12e7-4236-a677-907fc9e0c5f6)

### **Help Wanted** 
The blueprint will be delivered with a basic sample of how to integrate with the stack, but we have several other ideas for use cases that can be built. We are hoping to have community help during the upcoming hackathon to develop on top of this blueprint.

*We understand that there are safety and security implications with the orchestration of this use case, we will address this in phase 2.

**Comment by nacidai** [comment]
Thank you for your submission.  Can you comment on:

-  who will be in charge of maintaining this blueprint and the expected members.
- A list/links to the SDV projects that will be included
- Other technologies worth mentioning

Also, would it be ok for you to present the blueprint at the next Blueprints zoom call (Nov 7, 3PM CEST)?

**Comment by ladatz** [comment]
- Expected member companies: Phase 1: Microsoft, Elektrobit, Red Hat, Phase 2: ETAS, Cummins
- Projects: 
    - [Eclipse Agemo](https://github.com/eclipse-chariott/Agemo)
    - [Eclipse Chariott](https://github.com/eclipse-chariott/chariott)
    - [Eclipse Freyja](https://github.com/eclipse-ibeji/freyja/)
    - [Eclipse Ibeji](https://github.com/eclipse-ibeji/ibeji)
    - [Eclipse Ankaios](https://eclipse-ankaios.github.io/ankaios)
    - [Eclipse BlueChi](https://github.com/containers/bluechi)

Phase 2:
    -[Eclipse Kanto](https://eclipse.dev/kanto/)

- Other technologies: For Phase 2 and 3: Autosar applications, Cloud connectors, OTA

**Comment by nacidai** [comment]
I will kickoff the voting process to make the Software Orchestration a new blueprint:

+1

**Comment by iarmac** [comment]
+1

**Comment by windsource** [comment]
+1

**Comment by sophokles73** [comment]
+1

**Comment by badiiennouri1987** [comment]
+1

**Comment by AnotherDaniel** [comment]
+1

**Comment by nacidai** [comment]
7 (+1),  0 (-1)

The proposal has been accepted.   @fprezado @ladatz   

Please provide the following details so that I can create a request at the Eclipse EMO help desk to create a repository and add the initial committers for your blueprint:

**Blueprint name:** 
**Blueprint repository name:**
  ((must be a valid github repository name)
**List of initial committers:** 
        (Name, Email)
         If they are not already, all committers will become committer members of Eclipse Foundation and accept its policies

**Comment by fprezado** [comment]
thanks @nacidai , all for the comments, feedback and voting.

we will reply back with the details.

**Comment by ladatz** [comment]
**Blueprint name:** Software Orchestration blueprint
**Blueprint repository name:** software-orchestration
**List of initial committers:**
Lauren Datz, Jordan Chiu, Devin Kelley, Filipe Prezado, William Lyles, Liviu Tiganus, Holger Dormann, Oliver Klapper, Chatree Akasarn, Leonardo Rosetti, Michael Engel

@nacidai do you need email addresses or GitHub aliases for the committers?

**Comment by nacidai** [comment]
> **Blueprint name:** Software Orchestration blueprint **Blueprint repository name:** software-orchestration **List of initial committers:** Lauren Datz, Jordan Chiu, Devin Kelley, Filipe Prezado, William Lyles, Liviu Tiganus, Holger Dormann, Oliver Klapper, Chatree Akasarn, Leonardo Rosetti, Michael Engel
> 
> @nacidai do you need email addresses or GitHub aliases for the committers?
  Yes, also in order to become committers they should have an eclipse account with the email provided and  sign the ECA (eclipse committer agreement at  https://portal.eclipse.org)

**Comment by ladatz** [comment]
@nacidai Here are the email addresses. Please let me know if you need more information 

List of initial committers:
Lauren Datz (ladatz@microsoft.com), Jordan Chiu (jordanchiu@microsoft.com), Devin Kelley (dekelle@microsoft.com), Filipe Prezado (fprezado@hotmail.com), William Lyles (wilyle@microsoft.com), Liviu Tiganus (liviut@microsoft.com), Holger Dormann (holger.dorman@elektrobit.com), Oliver Klapper (oliver.klapper@elektrobit.com), Chatree Akasarn (chatree.akasarn@elektrobit.com), Leonardo Rosetti (lrossett@redhat.com), Michael Engel (mengel@redhat.com)

**Comment by nacidai** [comment]
I have created a request with the eclipse emo helpdesk. We can follow the progress there.  Please check the issue and subscribe.  EMO may have questions and requests.

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3979

**Comment by nacidai** [comment]
Congrats. Your repository has been created!  

https://github.com/eclipse-sdv-blueprints/software-orchestration

Happy blueprinting!
