### ISSUE TITLE
Insurance and Data Exchange

### ISSUE THREAD

**Issue by nacidai** [eclipse-sdv-blueprints/blueprints#8]
This proposal is brought forward  Mario Ortagon/microsoft  

A showcase for integrating Eclipse Software Defined Vehicle (SDV) and Eclipse Dataspaces for insurance applications. Enable exchange of vehicle and risk events to support risk assessment, underwriting processes and customer experiences

Identification of common driver risk events (maneuver detection) such as tailgating or speeding using CAN bus signals. Data capture / snapshotting and transmission of risk events to a telematics platform using MQTT pub. Data storage in a Insurance Landing Zone. Data exchange using Eclipse Dataspace components between two entities representing the OEM and the Insurance Platform

<img width="1020" alt="Screenshot 2023-10-17 at 10 58 42" src="https://github.com/eclipse-sdv-blueprints/blueprints/assets/1357299/42661eeb-09d2-4106-b26e-64f830646932">

Projects involved are:

- Eclipse Charriot 
- Eclipse Ibeji
- Eclipse Kuksa
- Eclipse Dataspaces
- MQTT

**Comment by nacidai** [comment]
@msmarioo is the coordinator for this proposal

**Comment by msmarioo** [comment]
As part of the blueprint we will leverage the upcoming blueprint for "Software Orchestration" that includes a "base" SDV distribution that leverages the above-mentioned component. This blueprint will concentrate on the Event detector application and the definition of 'Risk Events" from the point of view of an insurance company. It will also include the necessary code to create a basic landing zone and pipeline for processing the data for exchange using EDC.

The maintainer of this blueprint is @msmarioo

Commiters
- Anneke Minke
- Jannis Adrian Felix de Veer
- Pascal Godejohann
- Lisa Nussbaum
- 
(github handles tbd)

This project will create a DTDL based on the COVESA Signal Specification and will have a provider that will replay data at CAN speeds. The detectors will create events based on the signal data. Events will be transmitted using MQTT.

![image](https://github.com/eclipse-sdv-blueprints/blueprints/assets/73257383/a2ad57dd-9113-4b20-a0c8-a0ecc2a872f7)

**Comment by msmarioo** [comment]
The project will also include a proposal for a processing pipeline required to transform a "insurance event" into a "Insurance Data Product", as well as sample implementations for both a batched, periodic data transmission (for driving behavior events) as well as a live notification for the "First Notification of Loss" event.

The project will include a sample deployment of the [Eclipse Dataspaces Components] from the [Eclipse Dataspace Working Group](https://www.eclipse.org/org/workinggroups/dataspace-charter.php#:~:text=The%20mission%20of%20the%20Eclipse%20Dataspace%20Working%20Group,open-source%20components%20based%20on%20open%20standards%20for%20dataspaces.) that demonstrates communication between an Automotive OEM and an Insurance Company.

![image](https://github.com/eclipse-sdv-blueprints/blueprints/assets/73257383/3d9e60e5-6a8e-4066-a3ce-944390d3eb15)

Note: The diagram shows Azure technology (EG, EH, FA, ADLS2), but equivalent open-source components will be considered.

**Comment by msmarioo** [comment]
Initial committers to the project

Mario Ortegon - Microsoft - @msmarioo 
Anneke Minke - HDI - @annmin
Jannis Adrian Felix de Veer - HDI - @jafdeveer

**Comment by nacidai** [comment]
> Initial committers to the project
> 
> Mario Ortegon - Microsoft - @msmarioo Anneke Minke - HDI - @annmin - [anneke.minke@hdi.de](mailto:anneke.minke@hdi.de) Jannis Adrian Felix de Veer - HDI - @jafdeveer - [jannis.deveer@hdi.de](mailto:jannis.deveer@hdi.de)

Issue has been created with Eclipse Helpdesk.  You can track it at:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4162

**Comment by nacidai** [comment]
@msmarioo @annmin  @jafdeveer  please let me know when you have created your eclipse accounts (https://accounts.eclipse.org/user/register?destination=user)  so that I can continue with the nomination.  Please confirm here  wit the email you use for the eclipse account.

**Comment by nacidai** [comment]
> @msmarioo @annmin @jafdeveer please let me know when you have created your eclipse accounts (https://accounts.eclipse.org/user/register?destination=user) so that I can continue with the nomination. Please confirm here wit the email you use for the eclipse account.

I have started the nomination process as required by the eclipse foundation.  Please vote to accept Annike, Mario and Jannis as new committers to Insurance blueprint

Eclipse SDV Blueprints project committers can click the election link below
to vote.

- Election:

  - https://projects.eclipse.org/projects/automotive.sdv-blueprints/elections/election-jannis-de-veer-committer-eclipse-sdv-blueprints
  - https://projects.eclipse.org/projects/automotive.sdv-blueprints/elections/election-anneke-minke-committer-eclipse-sdv-blueprints
  -  Mario's nomination will follow once he completes ECA

- Project: 
  - https://projects.eclipse.org/projects/automotive.sdv-blueprints

**Comment by nacidai** [comment]
The election process for @msmarioo has been restarted:

https://projects.eclipse.org/projects/automotive.sdv-blueprints/elections/election-mario-alberto-ortegon-cabrera-committer-0
